server:
  port: 8086

spring:
  devtools:
    restart:
      enabled: true
  web:
    resources:
      static-locations:
        - file:src/main/resources/static
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/taco_db
    username: taco
    password: taco123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  jwt:
    secret: adkfjlwjkelfhiweffojdknlsdifjeklweifjalsieusiaaaaajdksss